### ISSUE TITLE
Function usage in redefinition crashes

### ISSUE THREAD

**Issue by Mizugola** [gura-lang/gura#5]
`print(a)={
    print(a+"\n");
}`

Using the function in the redefinition will make the program crashes.

**Comment by ypsitau** [comment]
This code results in a recursion that causes an infinite loop without doing anything because the  `print(a+"\n")` in the function body will call that defining function `print(a)` itself. Please define the function with a different name than `print` to avoid the problem.

FYI: there is a function `println()` that prints a string appended with a line-feed character.

**Comment by Mizugola** [comment]
Yup, I didn't know if it this behaviour was normal so I reported it as an issue :) Thanks
