### ISSUE TITLE
Module http - Set connect timeout

### ISSUE THREAD

**Issue by ohtejera** [gura-lang/gura#8]
Hi,

I used the [http](http://www.gura-lang.org/document/reference/gura-lib-en/chapter-29.html#naviitem-selected) module and I saw that not exist a way to sets a specified timeout value to be use when opening a communications link to the resource referenced by the URL.

I am right?

Thank you.

**Comment by ypsitau** [comment]
Thank you for trying Gura. Unfortunately, you're right. The current `http` module has not been implemented with timeout function during connecting and transferring data.

Instead of `http` module, I recommend you to use `curl` module. Implemented with the well-known library named cURL, it provides more robust and practical way of Internet connection along with timeout function.

**Comment by ohtejera** [comment]
Hi,

Thank you for your response. I found the timeout (for the connect phase) option for the cURL module:

```
c = curl.easy_init()
c.setopt(curl.OPT_CONNECTTIMEOUT_MS, 5000)
```

Regards.
